# docker-compose.yml
version: '3.8'

services:
  vector-search:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/tmp/keys/sa-key.json:ro
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - LOCATION=${LOCATION}
      - BUCKET_NAME=${BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/sa-key.json
    command: uvicorn src.api.app:app --reload --host 0.0.0.0 --port 8080