# docker-compose.yml

services:
  vector-search:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      # Use absolute path for service account key
      - ./service-account-key.json:/tmp/keys/sa-key.json:ro
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - LOCATION=${LOCATION}
      - BUCKET_NAME=${BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/sa-key.json
    command: uvicorn src.api.app:app --reload --host 0.0.0.0 --port 8080
