services:
  gemini-search:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      # Use absolute path for service account key
      - ./service-account-key.json:/tmp/keys/sa-key.json:ro
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - LOCATION=${LOCATION}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/sa-key.json
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: uvicorn src.api.app:app --reload --host 0.0.0.0 --port 8080